name: smooth_chucker
description: An HTTP requests inspector with isolate support for better performance. Inspects HTTP(S) requests/responses in your app with Material 3 UI and advanced search capabilities.
version: 0.0.1
homepage: https://github.com/lkrjangid1/smooth_chucker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  http: ^1.1.0
  chopper: ^7.4.0
  share_plus: ^10.1.4
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.4+4
  material_color_utilities: ^0.11.1
  flutter_json_viewer: ^1.0.1
  provider: ^6.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


screenshots:
  - description: 'Home'
    path: screenshots/1.png
  - description: 'Search and filter'
    path: screenshots/2.png
  - description: 'Details page'
    path: screenshots/3.png